nohup: ignoring input
[2023/01/16 21:08:59] ppocr DEBUG: Namespace(alpha=1.0, benchmark=False, beta=1.0, cls_batch_num=6, cls_image_shape='3, 48, 192', cls_model_dir='/home/huxingjian/.paddleocr/whl/cls/ch_ppocr_mobile_v2.0_cls_infer', cls_thresh=0.9, cpu_threads=10, crop_res_save_dir='./output', det=True, det_algorithm='DB', det_box_type='quad', det_db_box_thresh=0.6, det_db_score_mode='fast', det_db_thresh=0.3, det_db_unclip_ratio=1.5, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='/home/huxingjian/.paddleocr/whl/det/ch/ch_PP-OCRv3_det_infer', det_pse_box_thresh=0.85, det_pse_min_area=16, det_pse_scale=1, det_pse_thresh=0, det_sast_nms_thresh=0.2, det_sast_score_thresh=0.5, draw_img_save_dir='./inference_results', drop_score=0.5, e2e_algorithm='PGNet', e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_limit_side_len=768, e2e_limit_type='max', e2e_model_dir=None, e2e_pgnet_mode='fast', e2e_pgnet_score_thresh=0.5, e2e_pgnet_valid_set='totaltext', enable_mkldnn=False, fourier_degree=5, gpu_mem=500, help='==SUPPRESS==', image_dir=None, image_orientation=False, ir_optim=True, kie_algorithm='LayoutXLM', label_list=['0', '180'], lang='ch', layout=True, layout_dict_path=None, layout_model_dir=None, layout_nms_threshold=0.5, layout_score_threshold=0.5, max_batch_size=10, max_text_length=25, merge_no_span_structure=True, min_subgraph_size=15, mode='structure', ocr=True, ocr_order_method=None, ocr_version='PP-OCRv3', output='./output', page_num=0, precision='fp32', process_id=0, re_model_dir=None, rec=True, rec_algorithm='SVTR_LCNet', rec_batch_num=6, rec_char_dict_path='/home/huxingjian/anaconda3/envs/pkuocr/lib/python3.7/site-packages/paddleocr/ppocr/utils/ppocr_keys_v1.txt', rec_image_inverse=True, rec_image_shape='3, 48, 320', rec_model_dir='/home/huxingjian/.paddleocr/whl/rec/ch/ch_PP-OCRv3_rec_infer', recovery=False, save_crop_res=False, save_log_path='./log_output/', scales=[8, 16, 32], ser_dict_path='../train_data/XFUND/class_list_xfun.txt', ser_model_dir=None, show_log=True, sr_batch_num=1, sr_image_shape='3, 32, 128', sr_model_dir=None, structure_version='PP-StructureV2', table=True, table_algorithm='TableAttn', table_char_dict_path=None, table_max_len=488, table_model_dir=None, total_process_num=1, type='ocr', use_angle_cls=True, use_dilation=False, use_gpu=False, use_mp=False, use_npu=False, use_onnx=False, use_pdf2docx_api=False, use_pdserving=False, use_space_char=True, use_tensorrt=False, use_visual_backbone=True, use_xpu=False, vis_font_path='./doc/fonts/simfang.ttf', warmup=False)
[2023/01/16 21:09:01] ppocr ERROR: When input a list of images, det must be false
[2023/01/16 21:09:01] ppocr DEBUG: dt_boxes num : 36, elapse : 0.89634108543396
[2023/01/16 21:09:02] ppocr DEBUG: cls num  : 36, elapse : 0.45304036140441895
[2023/01/16 21:09:11] ppocr DEBUG: rec_res num  : 36, elapse : 9.526216745376587
[2023/01/16 21:09:12] ppocr DEBUG: dt_boxes num : 36, elapse : 0.966306209564209
[2023/01/16 21:09:13] ppocr DEBUG: cls num  : 36, elapse : 0.38939833641052246
[2023/01/16 21:09:21] ppocr DEBUG: rec_res num  : 36, elapse : 8.610780239105225
[2023-01-16 21:09:21,995] ERROR in app: Exception on /predict [POST]
Traceback (most recent call last):
  File "/home/huxingjian/anaconda3/envs/pkuocr/lib/python3.7/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/huxingjian/anaconda3/envs/pkuocr/lib/python3.7/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/huxingjian/anaconda3/envs/pkuocr/lib/python3.7/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/huxingjian/anaconda3/envs/pkuocr/lib/python3.7/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "app.py", line 46, in predict
    res_dicts, vis_img = checker.readtext(img, details=True)
  File "/home/huxingjian/model/pkuocr/pku_ocr_paddle.py", line 176, in readtext
    angles = [[int(line[2][0]) for line in r] for r in result]
  File "/home/huxingjian/model/pkuocr/pku_ocr_paddle.py", line 176, in <listcomp>
    angles = [[int(line[2][0]) for line in r] for r in result]
  File "/home/huxingjian/model/pkuocr/pku_ocr_paddle.py", line 176, in <listcomp>
    angles = [[int(line[2][0]) for line in r] for r in result]
IndexError: invalid index to scalar variable.
